import { TransactionAction } from "@prisma/client"
import { TransactionInput } from "~/models/transactions.server"

export const repeatedTransactions: TransactionInput[] = [
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 12800,
    description: "rent for front department",
    month: "please fill",
    owner: "Tenant",
    type: "DEPOSIT",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 16000,
    description: "rent for big house",
    month: "please fill",
    owner: "Tenant",
    type: "DEPOSIT",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 8800,
    description: "rent for basement department",
    month: "please fill",
    owner: "Tenant",
    type: "DEPOSIT",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 900,
    description: "arnona department",
    month: "please fill",
    owner: "Tenant",
    type: "EXPENSE",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 750,
    description: "arnona basement",
    month: "please fill",
    owner: "Tenant",
    type: "EXPENSE",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 16000,
    description: "rent for front department",
    month: "please fill",
    owner: "Ran",
    type: "WITHDRAWAL",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 2600,
    description: "arnona",
    month: "please fill",
    owner: "Ran",
    type: "WITHDRAWAL",
    year: "please fill",
  },
]
