import { TransactionAction } from "@prisma/client"
import { TransactionInput } from "~/models/transactions.server"

export const repeatedTransactions: TransactionInput[] = [
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 5700,
    description: "rent for front department",
    month: "please fill",
    owner: "Tenant",
    type: "DEPOSIT",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 8000,
    description: "rent for big house",
    month: "please fill",
    owner: "Tenant",
    type: "DEPOSIT",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 3800,
    description: "rent for basement department",
    month: "please fill",
    owner: "Tenant",
    type: "DEPOSIT",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 450,
    description: "arnona department",
    month: "please fill",
    owner: "Tenant",
    type: "DEPOSIT",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 385,
    description: "arnona basement",
    month: "please fill",
    owner: "Tenant",
    type: "DEPOSIT",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 1304,
    description: "rent for basement department",
    month: "please fill",
    owner: "Tenant",
    type: "DEPOSIT",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 8000,
    description: "rent for front department",
    month: "please fill",
    owner: "Ran",
    type: "WITHDRAWAL",
    year: "please fill",
  },
  {
    action: TransactionAction.MONTHLY_BILL,
    amount: 1304,
    description: "arnona",
    month: "please fill",
    owner: "Ran",
    type: "WITHDRAWAL",
    year: "please fill",
  },
]
